### ISSUE TITLE
Only one blind is working at the time:(

### ISSUE THREAD

**Issue by jascdk** [buxtronix/esphome-am43#4]
Hi Bux

Until lately I noticed, that my BLE device connecting to the blind engines is not working properly. I have some problems controlling both blinds at the time ( I have 2 AM43 devices). I use a lolin32 board to control them. 

Have there been some changes to esphome, that causes this behavior? 

Are you running the newest esphome, and do you have some problems - and how many blinds do you control?

I can provide the yaml I have running now

All the best

Jacob / Denmark

**Comment by jascdk** [comment]
````
substitutions:
  device_name: 'cover-livingroom'
  friendly_name: 'Stue Gardin'
  device_description: "Styring af gardiner i stuen"
  log_level: debug
 
packages:
  device_base: !include common/base.yaml
  
esphome:
  name: ${device_name}
  comment: '${device_description}'
  project:
    name: "buxtronix.am43_blinds"
    version: "1.0.0"

esp32:
  board: lolin32  
#  board: wemos_d1_mini32
  
########################################################################################  

esp32_ble_tracker:

ble_client:
  - mac_address: 02:28:20:EA:14:74
    id: stue_am43_right
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to the right curtain");
  - mac_address: 02:C7:E1:7B:7B:1B
    id: stue_am43_left  
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to the left curtain");
            
cover:
  - platform: am43
    name: ${friendly_name} Højre
    id: livingroom_right
    ble_client_id: stue_am43_right
    pin: 8888
  
  
  - platform: am43
    name: ${friendly_name} Venstre"
    id: livingroom_left
    ble_client_id: stue_am43_left 
    pin: 8888

sensor:
  - platform: am43
    ble_client_id: stue_am43_right
    battery_level:
      name: ${friendly_name} Højre Battery
    illuminance:
      name: ${friendly_name} Højre Light
    update_interval: 120s
  
  
  - platform: am43
    ble_client_id: stue_am43_left
    battery_level:
      name: ${friendly_name} Venstre Battery
    illuminance:
      name: ${friendly_name} Venstre Light
    update_interval: 120s 

switch:
  - platform: ble_client
    name: ${friendly_name} Højre
    id: switch_right
    ble_client_id: stue_am43_right
  
  
  - platform: ble_client
    name: ${friendly_name} Venstre
    id: switch_left
    ble_client_id: stue_am43_left
    
#status_led:
#  pin:
#    number: 5
#    inverted: true
    
#######################################
#  Sun specific Config Begins Below   #
#######################################  
  
sun:
  latitude: 55.243408
  longitude: 9.440710
  
  on_sunrise:
    then:
      - logger.log: Good morning - Covers will now open!
      - switch.turn_on: switch_right
      - switch.turn_on: switch_left
      - delay: 2min
      - cover.open: livingroom_right
      - cover.open: livingroom_left
      - delay: 2min
      - switch.turn_off: switch_right
      - switch.turn_off: switch_left
      
    
  on_sunset:
    then:
      - logger.log: Good evening - Covers will now close!
      - switch.turn_on: switch_right
      - switch.turn_on: switch_left
      - delay: 2min
      - cover.close: livingroom_right
      - cover.close: livingroom_left
      - delay: 2min
      - switch.turn_off: switch_right
      - switch.turn_off: switch_left

time:
  - platform: homeassistant 
  
text_sensor:
  - platform: sun
    name: Sun Next Sunrise
    type: sunrise
    icon: mdi:weather-sunset-up
  - platform: sun
    name: Sun Next Sunset
    type: sunset 
    icon: mdi:weather-sunset-down

**Comment by brainboost** [comment]
can be related to the issue https://github.com/esphome/issues/issues/3267

**Comment by jascdk** [comment]
Problem resolved in Esphome version 2022.11.2 - yay :D

**Comment by thiagaosalles** [comment]
Hello, how are you? Thank you very much for your work. I'm super noob about this part and I'm really wanting to automate my curtains. I already installed all the HA, ESPH, MQTT devices but I still can't visualize my curtains. Did you need to physically modify the devices? Is it possible to flash or pair them going bluetooh?
